### ISSUE TITLE
Duplicate messages, and it seems like they get stuck?

### ISSUE THREAD

**Issue by mrjones2014** [j-hui/fidget.nvim#12]
These messages don't go away. Sometimes there is only one message for each server, sometimes more.

I'm not sure but I think this bug gets triggered after getting an error as described in #8 

![CleanShot-2022-01-26-at-06 52 04](https://user-images.githubusercontent.com/8648891/151158519-ee4cc079-ac60-43c2-a3ab-ff837f5492b7.png)

**Comment by mystilleef** [comment]
See jose-elias-alvarez/null-ls.nvim#619 for a possible fix.

**Comment by Gelio** [comment]
I am facing the same problem even with https://github.com/jose-elias-alvarez/null-ls.nvim/pull/619

![image](https://user-images.githubusercontent.com/889383/151305067-8d485d72-326d-44c4-a53a-bee545e256bd.png)

![image](https://user-images.githubusercontent.com/889383/151305283-87ac4ca3-0f69-4f15-8507-768fb2efb8ad.png)

The error message no longer appears (that was fixed by https://github.com/jose-elias-alvarez/null-ls.nvim/pull/619), but the messages are still duplicated. I have noticed this only happens with null-ls

**Comment by mrjones2014** [comment]
Yeah I think you might be right about this being a duplicate of #10. I'll close this one.
