### ISSUE TITLE
spammy Diagnosing messages

### ISSUE THREAD

**Issue by davidosomething** [j-hui/fidget.nvim#122]
with diagnostics on (whether or not you have it to update on insert), we constantly get Diagnosing started/completed messages (workdone progress?)

would like a way to filter out messages, by kind, type, regex, etc.

**Comment by dbalatero** [comment]
For more context, I'm finding the `lua_ls` LSP server (which I imagine many Neovim users have enabled) can spam a bunch of messages like this:

![Screenshot of many messages](https://user-images.githubusercontent.com/59429/227749106-81eedea5-4e90-435b-b6cd-22321621a1c6.png)

This is on the smaller side–I've seen a stack of up to 15 duplicate messages like this today.

**Comment by dbalatero** [comment]
Also, taking inspiration from other editors, I think VSCode will basically just show 1 message at a time in the bar, instead of stacking up every single event as individual UI elements:

![image](https://user-images.githubusercontent.com/59429/227974061-eab44abc-6813-4099-82cf-3aa6242e1b43.png)

The tradeoff here is that you only see one message at a time.

It's worth probably checking in with users whether they _need_ to see every event individually, or just want an overall view of "what is my LSP server doing right now?"

For me personally, I probably just need the overall view and not the granularity that individual messages provide, but maybe others (@davidosomething, lurkers) can provide more color here as well.

**Comment by j-hui** [comment]
@dbalatero Thanks for your detailed thoughts! I think you're right that filter logic is more powerful and fine-grained, but is also complex and often unnecessarily powerful. I like the simplicity of just limiting the number of UI messages, though as a user I'd like also like to limit the number of LSP messages coming from _each_ LSP server.

A _separate_ issue is the fact that many of the messages are duplicated, and don't need separate entries. I think client-side deduplication should also be a feature though ideally this is something the server doesn't do in the first place. If you haven't already, please file an issue with the LSP server first (I suspect there's less visibility for this issue because many other progress UIs only show one message at a time).

For some context: I had implemented fidget.nvim in the first place precisely because I didn't like that existing plugins like [arkav/lualine-lsp-progress](https://github.com/arkav/lualine-lsp-progress) could only show a single message a time. The lsp server I use most often is Haskell Language Server, which takes a ridiculously long time to start, and so having very visible LSP messages was (and still is) important to me. As such, I'm quite desensitized to spammy LSP progress messages. But that's not to say they don't annoy me, I've just learned to live with them for now.

My plan (which I have procrastinated on for far too long) is to rewrite fidget from the ground up as a reuseable UI framework, with first-class support for consuming LSP progress messages. Option 1️⃣ will fall under the configuration for the specific LSP progress message component; option 2️⃣ will belong to the UI component. I'm still thinking about how best to structure this plugin (because I'd like it to be extensible and reuseable; see #62), and I also want to address #52 while I'm at it to make this plugin play nice with other consumers of LSP progress messages. I don't have a concrete timeline for this but I _hope_ to have something out by June this year.

**Comment by desaster** [comment]
I digged into fidget.nvim a bit to see if the diagnostics messages could be filtered out easily, and below is a snippet of code I came up with.

To clarify, my goal would be to:
* See messages when stuff is "initializing"
* Block out all (diagnostics) messages during actual use to reduce distraction

I don't necessarily like this approach, since it indeed has all the cons [dbalatero](https://github.com/dbalatero) listed. Unfortunately it seems there's no generic method to recognize "diagnostics" messages, since I believe the "title" could be anything?

I don't like offloading the filtering to user, especially since my configuration is already hundreds of lines of code just to get a basic neovim setup going.

But I don't see any other way to do it, so here's the snippet:

```diff
--- fidget.nvim/lua/fidget.lua	2023-03-28 11:27:47.176862227 +0300
+++ fidget-modified.nvim/lua/fidget.lua	2023-03-28 11:28:01.364968991 +0300
@@ -69,6 +69,7 @@
 }

 local fidgets = {}
+local ignored_tasks = {}


 local function ignore_E523(callable)
@@ -428,6 +429,24 @@
     return
   end

+  -- if filter matches, ignore future notifications from this task
+  if val.kind == 'begin' and options.filter then
+    if options.filter(client_name, val.title) ~= true then
+      ignored_tasks[task] = {}
+      return
+    end
+  end
+
+  -- clean up ignore list
+  if val.kind == 'end' and ignored_tasks[task] ~= nil then
+    ignored_tasks[task] = nil
+    return
+  end
+
+  if ignored_tasks[task] then
+    return
+  end
+
   -- Create entry if missing
   if fidgets[client_key] == nil then
     fidgets[client_key] = new_fidget(client_key, client_name)

```

And example configuration:

```lua
fidget.setup {
  filter = function(client, title)
    if client == 'null-ls' and title == 'diagnostics' then
      return false
    end
    return true
  end
}
```

**Comment by dbalatero** [comment]
@j-hui Sounds like we should wait on this issue until there's an internal refactor?

**Comment by GiuseppeMP** [comment]
I handled this using task format, I know it's not the right way, but it resolved my problems of insert mode spam of validate documents tasks.

```
-- function to format each task line
task = 
        function(task_name, message, percentage)
            if task_name == 'Validate documents' then return nil end
            return string.format(
                "%s%s [%s]",
                message,
                percentage and string.format(" (%s%%)", percentage) or "",
                task_name
            )
        end,
```

**Comment by pyrho** [comment]
Hey y'all,

Based on @dbalatero 's  Option 2️⃣  I've created a PR (#127) to implement this setting, thanks for the detailed comparision btw.

Cheers.

**Comment by j-hui** [comment]
Closed by #127 ; please check out the `legacy` tag, where @pyrho's commit is merged.

**Comment by ignamartinoli** [comment]
For some reason it doesn't work with my config:

```lua
{
	'j-hui/fidget.nvim',
	dependencies = 'neovim/nvim-lspconfig',
	event = 'LspAttach',
	opts = {
		fmt = {
			max_messages = 2
		}
	},
	tag = 'legacy'
},
```

If I set the `tag` to `'main'` it still shows the same problem.

**Comment by mawkler** [comment]
I'm having the same issue as @ignamartinoli
