### ISSUE TITLE
Relative to the editor, not the current buffer

### ISSUE THREAD

**Issue by wookayin** [j-hui/fidget.nvim#13]
It would be great to have the fidget notifications shown on relative to the entire windows rather than to the current buffer.

For example, when you have two windows [NERDTree || foo.py || bar.py] and LSP messages are shown for a python buffer -- the notifications on the right bottom will move around as you switch to different windows. Even on the NERDTree windows as well (which is not a even LSP-related buffer).

Regarding this, I think showing status messages for the associated buffers only would also make sense (the current behavior is that all the messages would be shown in the current active window), but this could be tracked as a different issue.

**Comment by j-hui** [comment]
#18 doesn't directly implement your suggestion, but should at least suppress notifications on unrelated buffers.

I was going to attempt your suggestion to make the position/alignment relative to the whole editor, until (1) I couldn't figure out how to obtain the editor height (I probably just need to dig through more documentation), and (2) it would still cause LSP messages to be overlaid on top of unrelated buffers, say if you had [foo.py || bar.py || NERDTree].

Let me know #18 addresses your problem. I'm hoping not to position the fidgets globally, because that's beginning to overstep into popups/notifications territory.

**Comment by levouh** [comment]
>I couldn't figure out how to obtain the editor height

`vim.opt.lines:get()` would get you the height, and `vim.opt.columns:get()` gets you the width.

**Comment by j-hui** [comment]
Ah I didn't realize about `lines`, I was grepping around for "row" and "height" and turning up empty lol. Thanks!
