### ISSUE TITLE
feat: support notification history

### ISSUE THREAD

**Issue by davidosomething** [j-hui/fidget.nvim#149]
[nvim-notify](https://github.com/rcarriga/nvim-notify) captures notifications so you can review them in a `:Notifications` command

would be nice if fidget did the same, maybe in `:FidgetNotifications`

i plan to use both and my use case would be:
- general notifications to nvim-notify via `vim.notify()`
- lsp notifications to fidget

**Comment by j-hui** [comment]
Certainly! This is actually something I already had in mind, but I didn't want to work on it until I decide on the right mechanism for omitting notifications from history (e.g., to ignore progress notifications, which some may consider spammy).

Also I want to do it as a subcommand system (e.g., something like `:Fidget history` rather than `:FidgetHistory`).

Also I want to support using Telescope as a notifications viewer (:

**Comment by j-hui** [comment]
Now, run `require("fidget.notification").show_history()` to see the history in the echo buffer; or, just use `get_history()` to get a list of `HistoryItem`s that you can consume or print out yourself. I will create separate issues for the subcommand system and Telescope integration.
