### ISSUE TITLE
highlights jump around a lot

### ISSUE THREAD

**Issue by 0xAdk** [j-hui/fidget.nvim#156]
min config:
```lua
local plug = vim.env.HOME .. '/.local/share/nvim/lazy'

vim.opt.rtp:append {
	plug .. '/nvim-lspconfig',
	plug .. '/fidget.nvim',
}

require 'fidget'.setup {}
require 'lspconfig'.rust_analyzer.setup {}
```

https://github.com/j-hui/fidget.nvim/assets/29005635/b4a5a39a-f875-4589-bb5f-2744fcdb1c51

**Comment by j-hui** [comment]
There's certainly something wrong with the way the highlights are being applied here, with this minimal config I see the issue you report:

![image](https://github.com/j-hui/fidget.nvim/assets/11800204/ec01c762-b0c6-4344-ba1f-9af63f42d7cb)
![image](https://github.com/j-hui/fidget.nvim/assets/11800204/ec6d5869-e26b-4ed1-9e15-4de45dfde264)

I'll look into it.

**Comment by j-hui** [comment]
Update: the bug is probably coming from `notification/window.lua`, when I'm computing what the offset should be after `:right`-justifying the window text. In particular, setting `right_col = nil` (which effectively shuts off `:right`-justification) avoids the issue:

![image](https://github.com/j-hui/fidget.nvim/assets/11800204/0475898d-a87a-4e62-8b5a-c8f93dae6fa3)

**Comment by 0xAdk** [comment]
is there a reason to use :right, instead of just computing the offset and adding spaces?

**Comment by j-hui** [comment]
I did this because I wanted to avoid repeated string operations in Lua. The idea was to dump the set of non-padded lines into a buffer, and let Neovim handle the right-justification in-place and all at once. (The ability to do this was also what motivated the use of an intermediate NotificationView that abstracts out padding concerns). 

But thinking about it again now, I no longer think that’s the right way to go about it, especially since this overhead is unlikely to be large in the first place. And I’m sure calling `:right` incurs some constant overhead of its own, since it’s meant to be an interactive Vim command. And worst of all, I’m not sure how to benchmark any of this, so this micro-optimization is certainly premature.

I’ll reimplement this to pad each line in Lua at some point and see if that makes the highlighting any more reliable (though I’m still not entirely sure what the root cause of the issue is).

**Comment by j-hui** [comment]
Wait, @0xAdk what is your tab width set to?

I was looking back through the `legacy` code and saw this: https://github.com/j-hui/fidget.nvim/blob/legacy/lua/fidget.lua#L175

and now I’m wondering if it’s because there’s some tabs being introduced somewhere that’s messing with the width calculations..

**Comment by 0xAdk** [comment]
4 by default, but I also have `guess-indent.nvim` installed

**Comment by 0xAdk** [comment]
assuming it's an option that fixed this in your config could try doing a binary search (assuming you have them all in one place)

that's how I found the scrolloff issue

**Comment by j-hui** [comment]
Yep I just tested it, the issue was that `:right` adds padding according to your various `tab` settings, so it was adding `\t` characters to the buffer, which are of byte-length 1 but display width `tabwidth` (or whatever the setting was).

**Comment by 0xAdk** [comment]
that's odd since the pr for not using `:right` didn't fix this for me (that's why I didn't mention it here)

**Comment by j-hui** [comment]
> that's odd since the pr for not using :right didn't fix this for me (that's why I didn't mention it here)
>
> edit: maybe I made a mistake in the pr and broke the highlights in a different way? I can't tell since the colors just always look broken to me

Yeah I think that was it XD
