### ISSUE TITLE
Fidget not 100% right-aligned

### ISSUE THREAD

**Issue by matze** [j-hui/fidget.nvim#16]
It's already visible in the demo gif that the fidget itself is not fully aligned with the right border the same way the tasks are. There are two spaces separating `rust_analyzer` from the border.

**Comment by j-hui** [comment]
I think this is caused by `string.format` not understanding the displayed length of a non-ASCII icon.

When I changed the spinner text to:

```lua
  text = {
    spinner = {"a", "b", "c"},
    done = "ok",
}
```
I no longer see the alignment issue.

![image](https://user-images.githubusercontent.com/11800204/151432936-8c0c206e-b867-44fc-8a40-c03851a51f1a.png)

I'll look into fixes though I'm aware non-ASCII lengths tend to be headscratchers.

This is also probably related to #3

**Comment by matze** [comment]
Yay, thanks! :partying_face:
