### ISSUE TITLE
feat: add nvim-tree awareness to avoid space collisions

### ISSUE THREAD

**Issue by hlmtre** [j-hui/fidget.nvim#163]
Have just moved off fidget.nvim's `legacy` tag and am very excited! I have discovered a small bug - fidget draws over the nvim-tree window. See below screenshot.

[https://aql.ink/7a49ff07.png](https://aql.ink/7a49ff07.png)

It appears to do this whether or not nvim-tree is open before or after fidget's first appearance in that session of nvim.

**Comment by j-hui** [comment]
Ugh, that’s because Fidget now uses editor-relative positioning and doesn’t know that it’s fighting for real estate with nvim-tree.

I’ll have to think about how to fix this. The pragmatic way is to teach Fidget to be aware of nvim-tree, but I’m wondering if there’s any generic way to avoid buffer collisions without having to teach Fidget about every tray-style plugin out there.

**Comment by hlmtre** [comment]
Perhaps a reasonable partial/temporary solution would be to give fidget an option to be offset from the right, specified in its configuration.

**Comment by j-hui** [comment]
Yeah, that would be the way to do it.

I was reading up on the nvim-tree API and it’s definitely doable for that one plugin at least. 

(Note to self: other plugins: trouble.nvim, treesitter playground, aerial (?), telescope… ugh there’s so many.)

**Comment by fitrh** [comment]
Is there a reason why the window-relative options are not currently exposed?

**Comment by j-hui** [comment]
@fitrh because I didn't get around to testing it yet...

Anyway, I just pushed a commit that adds this feature

**Comment by hlmtre** [comment]
[Brilliant!](https://aql.ink/67080598.png)

**Comment by hlmtre** [comment]
Thanks @j-hui. I looked through the commit and didn't realize neovim offered an API that would make for such a simple fix. Nicely done!

**Comment by j-hui** [comment]
Also, update: I added 22b2ed8 to expose an API for dynamically adjusting the horizontal offset, but still need to figure out how to integrate that with nvim-tree (I'm not sure how to [query the window size](https://github.com/nvim-tree/nvim-tree.lua/discussions/2532)).

I'm going to remove the bug label from this issue since a workaround exists, but I'll keep it open until Fidget properly integrates with nvim-tree (or until we decide to give up on that).

**Comment by j-hui** [comment]
GitHub path compression:
- Issue on nvim-tree: https://github.com/nvim-tree/nvim-tree.lua/issues/2544
- PR adding the proposed feature: https://github.com/nvim-tree/nvim-tree.lua/pull/2545

**Comment by kluen** [comment]
@j-hui Hi, have there been any new thoughts on how to solve this in a general way?
I would like for the text to not draw over my aerial.nvim window. However, I'm a bit hesitant to create ticket. As you said above, there are just so many plugins. Sounds like a lot of maintenance effort. :/
