### ISSUE TITLE
Spinner appearing twice

### ISSUE THREAD

**Issue by robbyki** [j-hui/fidget.nvim#56]
Trying to troubleshoot why my spinner is showing duplicate messaging. Using default configs. 
![spinner](https://user-images.githubusercontent.com/1027357/157507366-d095dc79-1565-416c-a9f7-e947e7caaa68.gif)

**Comment by anuvyklack** [comment]
![Screenshot-20220315120358-610x178](https://user-images.githubusercontent.com/13056013/158343276-441b690d-9648-4100-84b1-d2749bc3e0a7.png)

**Comment by akinsho** [comment]
Just a heads-up this isn't a bug in this plugin but actually the behaviour of sumneko it sends 2 notifications, I've seen elsewhere as it was raised as an issue elsewhere. I think it is by the author's design, but I don't really know the full rationale

**Comment by j-hui** [comment]
@akinsho interesting. I have noticed this being an issue with several other language servers as well (in particular, HLS seems to do this I think), but I haven't had the time to investigate this yet (I always thought this was a bug with Fidget xD)

If this was intentional on the part of the language server, I wonder if it's because the "expected" use case for these messages is that they are supposed to be displayed in a single line, and should ovewrite each other?

**Comment by robbyki** [comment]
don't experience this issue anymore

**Comment by anuvyklack** [comment]
I personally still have 2 workspaces loading.

**Comment by shaeinst** [comment]
can confirm
![image](https://user-images.githubusercontent.com/41078534/180263617-1eb198d9-cc16-4b2c-823a-37f6976a7cea.png)
