### ISSUE TITLE
Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by towry** [j-hui/fidget.nvim#86]
```txt
Error executing vim.schedule lua callback: ...are/nvim/site/pack/packer/opt/fidget.nvim/lua/fidget.lua:90: Error occured:
...are/nvim/site/pack/packer/opt/fidget.nvim/lua/fidget.lua:288: Vim:E322: line number out of range: 1 past the end
stack traceback:
	[C]: in function 'error'
	...are/nvim/site/pack/packer/opt/fidget.nvim/lua/fidget.lua:90: in function 'render_fidgets'
	...are/nvim/site/pack/packer/opt/fidget.nvim/lua/fidget.lua:222: in function 'fmt'
	...are/nvim/site/pack/packer/opt/fidget.nvim/lua/fidget.lua:328: in function 'do_spin'
	...are/nvim/site/pack/packer/opt/fidget.nvim/lua/fidget.lua:349: in function 'spin'
	...are/nvim/site/pack/packer/opt/fidget.nvim/lua/fidget.lua:340: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>%
```

This error happened when I exit(`:qa`) nvim during the LSP initialization of a server client.

<img width="364" alt="截屏2022-06-11 18 34 21" src="https://user-images.githubusercontent.com/8279858/173184235-a7d38d3f-9372-43cc-986e-6b3e4d95682c.png">

**Comment by aosterhage** [comment]
Same issue for me with clangd:

```
Error executing vim.schedule lua callback: ...m-data\site\pack\packer\start\fidget.nvim/lua/fidget.lua:90: Error occured:
...m-data\site\pack\packer\start\fidget.nvim/lua/fidget.lua:289: Vim:E322: line number out of range: 1 past the end
stack traceback:
        [C]: in function 'error'
        ...m-data\site\pack\packer\start\fidget.nvim/lua/fidget.lua:90: in function 'render_fidgets'
        ...m-data\site\pack\packer\start\fidget.nvim/lua/fidget.lua:222: in function 'fmt'
        ...m-data\site\pack\packer\start\fidget.nvim/lua/fidget.lua:329: in function 'do_spin'
        ...m-data\site\pack\packer\start\fidget.nvim/lua/fidget.lua:350: in function 'spin'
        ...m-data\site\pack\packer\start\fidget.nvim/lua/fidget.lua:341: in function 'fn'
        vim/_editor.lua:413: in function 'cb'
        vim/_editor.lua:262: in function <vim/_editor.lua:261>
```

I did confirm that I do not get this error if I let the indexing complete.

**Comment by j-hui** [comment]
I wanted to mention that I get this error regularly too. It's not bothered me significantly since it's just some screen noise when I quit, but it does signify some bigger issues with how Fidget's execution handles these edge cases. 

I do plan on addressing this with a rewrite of Fidget, but haven't found the time yet, so really sorry for the delay. If anyone finds a self-contained patch to get rid of this issue, I'll be happy to accept it.

**Comment by Akianonymus** [comment]
For the time being, i am using this autocmd to tackle this.

```lua
vim.api.nvim_create_autocmd("VimLeavePre", { command = [[silent! FidgetClose]] })
```

Basically closes fidget before exiting neovim, so no errors.

**Comment by wilriker** [comment]
Thank you for fixing this. I have to restart nvim several times a day (in my workflow) and this was very annoying (I even turned away from fidget.nvim until today because of this - seeing an unexpected error, exiting a program immediately caught my full attention and bound resources uselessly on my end).

**Comment by j-hui** [comment]
All credit goes to @Gelio !

Unless anyone is still encountering this error message, I'll consider this solved and close this issue.
